name: PhyloGame
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gdk-pixbuf=2.42.8
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gtk2=2.24.33
  - gts=0.7.6
  - importlib_resources=5.8.0
  - kernel-headers_linux-64=2.6.32
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libdeflate=1.12
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc=5.2.0
  - libgcc-ng=12.1.0
  - libgd=2.3.3
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.70.2
  - libgomp=12.1.0
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - librsvg=2.54.3
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - openssl=3.0.5
  - optuna=2.10.0
  - packaging=21.3
  - pango=1.50.7
  - pbr=5.9.0
  - pcre=8.45
  - pip=22.1.2
  - pthread-stubs=0.4
  - python=3.9.13
  - python-graphviz=0.19.1
  - python_abi=3.9
  - pyyaml=6.0
  - raxml-ng=1.1.0
  - readline=8.1.2
  - scipy=1.8.0
  - sqlalchemy=1.4.37
  - sqlite=3.38.5
  - stevedore=3.5.0
  - sysroot_linux-64=2.12
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - pip:
    - bio==1.3.2
    - biopython==1.79
    - biothings-client==0.2.6
    - ete3==3.1.2
    - joblib==1.1.0
    - jsonschema==4.4.0
    - libclang==14.0.1
    - lightgbm==3.3.1
    - matplotlib==3.5.0
    - numpy==1.19.5
    - opencv-python==4.5.5.64
    - pandas==1.1.5
    - peptides==0.2.1
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - seaborn==0.11.2
    - torch==1.10.0
