name: PhyloGame
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alembic=1.8.0
  - atk-1.0=2.36.0
  - attrs=21.4.0
  - autopage=0.5.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - blast=2.12.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cairo=1.16.0
  - cliff=3.10.1
  - cmaes=0.8.2
  - cmd2=2.3.3
  - colorama=0.4.5
  - colorlog=6.6.0
  - curl=7.83.1
  - entrez-direct=16.2
  - expat=2.4.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gdk-pixbuf=2.42.8
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gmp=6.2.1
  - graphite2=1.3.13
  - graphviz=4.0.0
  - greenlet=1.1.2
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=4.3.0
  - icu=70.1
  - importlib_resources=5.8.0
  - jpeg=9e
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.19.3
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libdeflate=1.12
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc=5.2.0
  - libgcc-ng=12.1.0
  - libgd=2.3.3
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.70.2
  - libgomp=12.1.0
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - librsvg=2.54.3
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - mako=1.2.0
  - mpi=1.0
  - ncurses=6.3
  - openmpi=4.1.4
  - openssl=3.0.5
  - optuna=2.10.0
  - packaging=21.3
  - pango=1.50.7
  - pbr=5.9.0
  - pcre=8.45
  - perl=5.32.1
  - perl-archive-tar=2.40
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.103
  - perl-compress-raw-zlib=2.105
  - perl-encode=3.17
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002002
  - perl-io-compress=2.106
  - perl-io-zlib=1.11
  - perl-json=4.06
  - perl-json-xs=2.34
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.236
  - perl-pathtools=3.40
  - perl-scalar-list-utils=1.62
  - perl-threaded=5.32.1
  - perl-types-serialiser=1.01
  - pip=22.1.2
  - pixman=0.40.0
  - plotly=5.9.0
  - prettytable=3.3.0
  - pthread-stubs=0.4
  - pyperclip=1.8.2
  - python=3.9.13
  - python-graphviz=0.19.1
  - python_abi=3.9
  - pyyaml=6.0
  - raxml-ng=1.1.0
  - readline=8.1.2
  - scipy=1.8.0
  - sqlalchemy=1.4.37
  - sqlite=3.38.5
  - stevedore=3.5.0
  - sysroot_linux-64=2.12
  - tenacity=8.0.1
  - tk=8.6.12
  - wcwidth=0.2.5
  - wget=1.20.3
  - wheel=0.37.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.0.0
    - aiosignal==1.2.0
    - ale-py==0.7.5
    - apscheduler==3.8.1
    - astunparse==1.6.3
    - autorom==0.4.2
    - autorom-accept-rom-license==0.4.2
    - backports-zoneinfo==0.2.1
    - bio==1.3.2
    - biopython==1.79
    - biothings-client==0.2.6
    - cachetools==5.0.0
    - certifi==2021.10.8
    - charset-normalizer==2.0.7
    - click==8.0.3
    - cloudpickle==2.0.0
    - cycler==0.11.0
    - cython==0.29.30
    - decorator==4.4.2
    - distlib==0.3.4
    - dm-tree==0.1.7
    - ete3==3.1.2
    - filelock==3.6.0
    - flask==2.0.2
    - flatbuffers==2.0
    - flatten-json==0.1.13
    - fonttools==4.28.1
    - frozenlist==1.3.0
    - gast==0.5.3
    - gensim==4.1.2
    - gmatch4py==0.2.5b0
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.43.0
    - gym==0.21.0
    - h5py==3.6.0
    - idna==3.3
    - imageio==2.17.0
    - importlib-metadata==4.8.1
    - importlib-resources==5.4.0
    - itsdangerous==2.0.1
    - jinja2==3.0.2
    - joblib==1.1.0
    - jsonschema==4.4.0
    - karateclub==1.2.2
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - libclang==14.0.1
    - lightgbm==3.3.1
    - lz4==4.0.0
    - markdown==3.3.7
    - markupsafe==2.0.1
    - matplotlib==3.5.0
    - memory-profiler==0.60.0
    - msgpack==1.0.3
    - mygene==3.2.2
    - networkx==2.6.3
    - nltk==3.7
    - nose==1.3.7
    - numpy==1.19.5
    - oauthlib==3.2.0
    - objgraph==3.5.0
    - opencv-python==4.5.5.64
    - opt-einsum==3.3.0
    - pandas==1.1.5
    - peptides==0.2.1
    - pillow==9.0.1
    - platformdirs==2.5.2
    - protobuf==3.20.1
    - psutil==5.9.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.23
    - pygsp==0.5.1
    - pympler==1.0.1
    - pyparsing==3.0.6
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - python-levenshtein==0.12.2
    - python-louvain==0.15
    - pytz==2021.3
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.3.0
    - ray==1.12.0
    - regex==2022.3.15
    - requests==2.26.0
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - seaborn==0.11.2
    - setuptools==66.1.1
    - setuptools-scm==6.3.2
    - six==1.16.0
    - sklearn==0.0
    - smart-open==5.2.1
    - stable-baselines3==1.5.0
    - tabulate==0.8.9
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5
    - tensorflow-io-gcs-filesystem==0.25.0
    - termcolor==1.1.0
    - textsplit==0.5
    - texttable==1.6.4
    - tf-estimator-nightly==2.8.0.dev2021122109
    - threadpoolctl==3.0.0
    - tifffile==2022.4.22
    - tomli==1.2.2
    - torch==1.10.0
    - tqdm==4.62.3
    - typing-extensions==3.10.0.2
    - tzdata==2021.5
    - tzlocal==4.1
    - urllib3==1.26.7
    - virtualenv==20.14.1
    - werkzeug==2.0.2
    - word2vec==0.11.1
    - wrapt==1.14.1
    - zipp==3.6.0
